task:
  submodules_script:
    - git submodule update --init --recursive

  matrix:
    - name: "Linux - TeX Live 2020"
      container:
        dockerfile: ci/texlive-2020-linux.Dockerfile
      env:
        PROTODIR: proto_tl2020

    - name: "Linux - TeX Live 2019"
      container:
        dockerfile: ci/texlive-2019-linux.Dockerfile
      env:
        PROTODIR: proto_tl2019

  install_script:
    - pdfinfo -v
    - compare -version
    - gs -v
    - pdflatex -version
    - tlmgr conf
    - make install CONTINUE=y
    - texhash

  test_script:
    - make -C test PYTHON=python3 PROTODIR=${PROTODIR}
